force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ABN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status - HL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#F3D904</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#FF0000</color>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#A53711</color>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Fraud/Dispute</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Application Incomplete</fullName>
            </value>
            <value>
                <fullName>Hold Debits</fullName>
            </value>
            <value>
                <fullName>Purge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>HL Client ID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>360 Membership</fullName>
            </value>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Accelerware - Sports Performance Systems</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>All Inn 1</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>ASSA</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>Billing Bureau</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Booking Boss</fullName>
            </value>
            <value>
                <fullName>Bookings Essential</fullName>
            </value>
            <value>
                <fullName>Business Of Motion</fullName>
            </value>
            <value>
                <fullName>Causeview</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Xestro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <description>Object holds CSA online templates</description>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA{00000000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CSAs</relationshipLabel>
    <relationshipName>CSAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EFTPOS_User__c/EFTPOS_User__c.object-meta.xml
<CustomObject>
    <description>This Objects is inteded to store the Multi-Mid Merchant relationship Owner - User.</description>
    <label>EFTPOS User</label>
    <nameField>
        <displayFormat>EFTPOS User - {0000000000}</displayFormat>
        <label>EFTPOS User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFTPOS Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EFTPOS_User__c/fields/EFTPOS_Device_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>EFTPOS_Device_Owner_Account__c</fullName>
    <description>Device Owner Account</description>
    <inlineHelpText>Device Owner Account</inlineHelpText>
    <label>EFTPOS Device Owner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EFTPOS Users</relationshipLabel>
    <relationshipName>EFTPOS_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EFTPOS_User__c/fields/EFTPOS_Device_Owner_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EFTPOS_Device_Owner_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>EFTPOS Device Owner Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EFTPOS Users (EFTPOS Device Owner Opportunity)</relationshipLabel>
    <relationshipName>EFTPOS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFTPOS_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status between Owner and User</description>
    <inlineHelpText>Status between Owner and User</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Owner Prefill Completed</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Settings__c/Global_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Settings</description>
    <label>Global Settings</label>
</CustomObject>

force-app/main/default/objects/Global_Settings__c/fields/SiteURL__c.field-meta.xml
<CustomField>
    <fullName>SiteURL__c</fullName>
    <description>get site url</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>get site url</inlineHelpText>
    <label>SiteURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <inlineHelpText>If you select Other - please specify details in field below.</inlineHelpText>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>ASSA</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>Better HQ</fullName>
            </value>
            <value>
                <fullName>Billing Bureau</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>Booking Boss</fullName>
            </value>
            <value>
                <fullName>Business Of Motion</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Client Connect</fullName>
            </value>
            <value>
                <fullName>Clouding Around</fullName>
            </value>
            <value>
                <fullName>CloudMasons</fullName>
            </value>
            <value>
                <fullName>Clubware</fullName>
            </value>
            <value>
                <fullName>Xestro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSA__c.field-meta.xml
<CustomField>
    <fullName>CSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the CSA created</inlineHelpText>
    <label>CSA</label>
    <referenceTo>CSA__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>Business of Motion</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Client Connect</fullName>
            </value>
            <value>
                <fullName>Clouding Around</fullName>
            </value>
            <value>
                <fullName>Clubworx</fullName>
            </value>
            <value>
                <fullName>Concise Digital</fullName>
            </value>
            <value>
                <fullName>Console Gateway</fullName>
            </value>
            <value>
                <fullName>CyberSource Direct</fullName>
            </value>
            <value>
                <fullName>DanceStudio-Pro</fullName>
            </value>
            <value>
                <fullName>DebtCol</fullName>
            </value>
            <value>
                <fullName>Xestro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillerMatchControllerTest.cls
@IsTest
public class BillerMatchControllerTest  { 
    @TestSetup
    static void setupTestData() {
        Global_Settings__c settings = new Global_Settings__c();
        settings.SiteURL__c = 'https://ezidebit--ezifull.sandbox.my.salesforce-sites.com/online';
        insert settings;
        
        // Create an owner account and opportunity
        Account ownerAccount = new Account(
            Name = 'Owner Account',
            Software__c = 'Xestro',
            Account_Status__c = 'Active',
            Client_Code__c = '001002003',
            ABN__c = '123456789'
        );
        insert ownerAccount;

        Contact con = new Contact(FirstName = 'Owner Con1', LastName = 'last name', Email = 'test@email.com', AccountId = ownerAccount.Id);
        insert con;

        Opportunity ownerOpportunity = new Opportunity(
            Name = 'Owner Opportunity',
            StageName = 'Transacting',
            CloseDate = Date.today(),
            AccountId = ownerAccount.Id
        );
        insert ownerOpportunity;

        CSA__c ownerCSA = new CSA__c(
            Opportunity__c = ownerOpportunity.Id
        );
        insert ownerCSA;

        ownerOpportunity.CSA__c = ownerCSA.Id;
        update ownerOpportunity;

        // Create a test Lead
        Lead testLead = new Lead(
            LastName = 'Test Lead1',
            Company = 'Test Company',
            Status = 'Open - Not Contacted',
            Software__c = 'Xestro'
        );
        insert testLead;

        // Create test EFTPOS_User__c
        EFTPOS_User__c eftposUser = new EFTPOS_User__c(
            EFTPOS_Device_Owner_Account__c = ownerAccount.Id,
            EFTPOS_Device_Owner_Opportunity__c = ownerOpportunity.Id,
            EFTPOS_Device_User_Lead__c = testLead.Id
        );
        
        insert eftposUser;
    }

    @IsTest
    static void testNoExistingBiller() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('NonExistingclientId', 'NonExistingBusinessNumber','', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfNoAcctMatch, result.message, 'Unexpected message returned');
    }

    @IsTest
    static void testSearchExistingBillerMulti() {
        // Create test Accounts with the same Client ID and Business Number
        Account account1 = new Account(
            Name = 'Account 1',
            Client_Code__c = '123',
            ABN__c = '456',
            Software__c = 'Xestro',
            Account_Status__c = 'Active'
        );
        Account account2 = new Account(
            Name = 'Account 2',
            Client_Code__c = '123',
            ABN__c = '456',
            Software__c = 'Xestro',
            Account_Status__c = 'Active'
        );
        insert new List<Account>{account1, account2};

        Lead testLead = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('123', '456', 'test@email.com', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfMultiAcctsMatch, result.message, 'Unexpected message returned');
    }

    @IsTest
    static void testOneExistingBillerWithMatchingSoftware() {
        // Create test Account
        Account validAccount = new Account(
            Name = 'Valid Account',
            Client_Code__c = '789',
            ABN__c = '012',
            Software__c = 'Xestro',
            Account_Status__c = 'Active'
        );
        insert validAccount;

        Contact con = new Contact(FirstName = 'Con2', LastName = 'last name', Email = 'test2@email.com', AccountId = validAccount.Id);
        insert con;

        Lead testLead = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('789', '012', 'test2@email.com', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfAcctMatch, result.message, 'Unexpected message returned');
        System.assertEquals('ProdAdd', result.proceedTo, 'Expected proceedTo to be ProdAdd');
    }

    @IsTest
    static void testOneExistingBillerWithNonMatchingSoftware() {
        // Create test Account with different software
        Account account = new Account(
            Name = 'Account with Different Software',
            Client_Code__c = '345',
            ABN__c = '678',
            Software__c = 'DifferentSoftware',
            Account_Status__c = 'Active'
        );
        insert account;

        Contact con = new Contact(FirstName = 'Con2', LastName = 'last name', Email = 'test2@email.com', AccountId = account.Id);
        insert con;

        Lead testLead = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('345', '678', 'test2@email.com', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfSoftwareUnmatch, result.message, 'Unexpected message returned');
        System.assertEquals('NormalCSA', result.proceedTo, 'Expected proceedTo to be NormalCSA');
    }

    @IsTest
    static void testOneExistingBillerInvalidStatus() {
        // Create test Account with invalid status
        Account invalidStatusAccount = new Account(
            Name = 'Invalid Status Account',
            Client_Code__c = '901',
            ABN__c = '234',
            Software__c = 'Xestro',
            Account_Status__c = 'Inactive'
        );
        insert invalidStatusAccount;

        Lead testLead = [SELECT Id FROM Lead LIMIT 1];

        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('901', '234', 'test@email.com', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfInvalidStatus, result.message, 'Unexpected message returned');
        System.assertEquals('NormalCSA', result.proceedTo, 'Expected proceedTo to be NormalCSA');
    }

    @IsTest
    static void testProceedToNormalCSAWithInvalidLead() {
        Test.startTest();
        try {
            BillerMatchController.proceedToNormalCSA('NonExistingLeadId');
        } catch (Exception ex) {
            System.assertEquals('Invalid id: NonExistingLeadId', ex.getMessage(), 'Expected error message when lead conversion fails');
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testProceedToNormalCSAExceptionHandling() {
        Test.startTest();
        try {
            BillerMatchController.proceedToNormalCSA('');
        } catch (Exception ex) {
            System.assertEquals('Lead ID cannot be blank.', ex.getMessage(), 'Expected error message when lead conversion fails');
        }
        Test.stopTest();
    }

    @IsTest
    static void testProceedToNormalCSA() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        Opportunity ownerOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        CSA__c ownerCSA = [SELECT Id FROM CSA__c LIMIT 1];

        Test.startTest();
        String result1 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        Test.stopTest();

        System.assert(result1.contains('https://ezidebit--ezifull.sandbox.my.salesforce-sites.com/online/kyc_yourbusiness?'), 'Unexpected result from ProceedToNormalCSA');
        String result2 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        System.assertEquals(result1, result2);
    }

    @IsTest
    static void testProceedToNormalCSA_PrefillProcess() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        Opportunity ownerOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        CSA__c ownerCSA = [SELECT Id FROM CSA__c LIMIT 1];
        EFTPOS_User__c eftposUser = [SELECT Id, Prefill_User_CSA__c FROM EFTPOS_User__c WHERE EFTPOS_Device_User_Lead__c = :testLead.Id LIMIT 1];
        eftposUser.Prefill_User_CSA__c = true;
        eftposUser.Status__c = 'Referred';
        eftposUser.Signup_ID__c = 'test_signup_id';
        update eftposUser;

        Test.startTest();
        String result1 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        Test.stopTest();

        System.assert(result1.contains('https://ezidebit--ezifull.sandbox.my.salesforce-sites.com/online/kyc_yourbusiness?'), 'Unexpected result from ProceedToNormalCSA');
        System.assert(result1.contains('signupId'), 'Unexpected result from ProceedToNormalCSA');
        String result2 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        System.assertEquals(result1, result2);
    }

    @IsTest
    static void testProceedToNormalCSA_PrefillCompleted() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        Opportunity ownerOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        CSA__c ownerCSA = [SELECT Id FROM CSA__c LIMIT 1];
        EFTPOS_User__c eftposUser = [SELECT Id, Prefill_User_CSA__c FROM EFTPOS_User__c WHERE EFTPOS_Device_User_Lead__c = :testLead.Id LIMIT 1];
        eftposUser.Prefill_User_CSA__c = true;
        eftposUser.Status__c = 'Owner Prefill Completed';
        eftposUser.Signup_ID__c = 'test_signup_id';
        update eftposUser;

        Test.startTest();
        String result1 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        Test.stopTest();

        System.assert(result1.contains('thank-you'), 'Unexpected result from ProceedToNormalCSA');
        String result2 = BillerMatchController.proceedToNormalCSA(testLead.Id);
        System.assertEquals(result1, result2);
    }

    @IsTest
    static void testProceedToProdAdd() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        Opportunity ownerOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
        CSA__c ownerCSA = [SELECT Id FROM CSA__c LIMIT 1];

        Test.startTest();
        String result = BillerMatchController.proceedToProdAdd(testLead.Id);
        Test.stopTest();

        System.assertEquals('Proceed to ProdAdd (TBA)', result, 'Unexpected result from proceedToProdAdd');
    }

    @IsTest
    static void testExistingBillerContactMatch() {
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        Test.startTest();
        BillerMatchController.BillerMatchWrapper result = BillerMatchController.searchExistingBiller('001002003', '123456789', 'test@email.com', testLead.Id, '');
        Test.stopTest();

        System.assert(result != null, 'Result should not be null');
        System.assertEquals(BillerMatchController.msgIfAcctMatch, result.message, 'Unexpected message returned');
        System.assertEquals('ProdAdd', result.proceedTo, 'Expected proceedTo to be ProdAdd');
    }
}