force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status - HL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <color>#F3D904</color>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <color>#FF0000</color>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#A53711</color>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Unapproved</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Fraud/Dispute</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Application Incomplete</fullName>
            </value>
            <value>
                <fullName>Hold Debits</fullName>
            </value>
            <value>
                <fullName>Purge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Code__c.field-meta.xml
<CustomField>
    <fullName>Client_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>HL Client ID</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>360 Membership</fullName>
            </value>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Accelerware - Sports Performance Systems</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>All Inn 1</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>ASSA</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>Billing Bureau</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Booking Boss</fullName>
            </value>
            <value>
                <fullName>Bookings Essential</fullName>
            </value>
            <value>
                <fullName>Business Of Motion</fullName>
            </value>
            <value>
                <fullName>Causeview</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unformatted_ABN__c.field-meta.xml
<CustomField>
    <fullName>Unformatted_ABN__c</fullName>
    <description>This is unformatted version for ABN field which removes all the blank spaces and makes it queriable in apex.</description>
    <formula>SUBSTITUTE(TRIM( ABN__c ) , &apos; &apos; , &apos;&apos;)</formula>
    <label>Unformatted ABN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Active Not Processing</fullName>
            </value>
            <value>
                <fullName>Agreement Review</fullName>
            </value>
            <value>
                <fullName>Amex notification</fullName>
            </value>
            <value>
                <fullName>Anniversary</fullName>
            </value>
            <value>
                <fullName>Anyone</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>HK chargeback</fullName>
                <label>Asia Chargeback</label>
            </value>
            <value>
                <fullName>HK RFI</fullName>
                <label>Asia RFI</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>AU BA Chargeback</fullName>
            </value>
            <value>
                <fullName>AU BA claim</fullName>
            </value>
            <value>
                <fullName>AU CC Chargeback</fullName>
            </value>
            <value>
                <fullName>AU CC RFI</fullName>
            </value>
            <value>
                <fullName>AU Chargeback</fullName>
            </value>
            <value>
                <fullName>AU Compliance</fullName>
            </value>
            <value>
                <fullName>BNZ</fullName>
            </value>
            <value>
                <fullName>Bpay</fullName>
            </value>
            <value>
                <fullName>Bpay Follow up</fullName>
            </value>
            <value>
                <fullName>Cancel my Account</fullName>
            </value>
            <value>
                <fullName>Change my Business Details</fullName>
            </value>
            <value>
                <fullName>Change my Details</fullName>
            </value>
            <value>
                <fullName>Change my Payer Details</fullName>
            </value>
            <value>
                <fullName>Change of Details Eway</fullName>
            </value>
            <value>
                <fullName>Change Of Entity</fullName>
            </value>
            <value>
                <fullName>Change of Fee Form</fullName>
            </value>
            <value>
                <fullName>Change of Ownership</fullName>
            </value>
            <value>
                <fullName>Change of Ownership/ABN</fullName>
            </value>
            <value>
                <fullName>Charge on my Statement</fullName>
            </value>
            <value>
                <fullName>Chat with Me Now</fullName>
            </value>
            <value>
                <fullName>Service (multi-MID)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ACMA</fullName>
            </value>
            <value>
                <fullName>Additional Products</fullName>
            </value>
            <value>
                <fullName>API access issues</fullName>
            </value>
            <value>
                <fullName>Awaiting Auth Signature</fullName>
            </value>
            <value>
                <fullName>Awaiting BNZ Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting ID</fullName>
            </value>
            <value>
                <fullName>Awaiting Merchant Info</fullName>
            </value>
            <value>
                <fullName>Bank Statement Missing / Invalid</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation Policy</fullName>
            </value>
            <value>
                <fullName>Change my Payer Details</fullName>
            </value>
            <value>
                <fullName>Change of ABN</fullName>
            </value>
            <value>
                <fullName>Change of Ownership</fullName>
            </value>
            <value>
                <fullName>Client Dishonour Fee</fullName>
            </value>
            <value>
                <fullName>Contact Details</fullName>
            </value>
            <value>
                <fullName>Copy of Client Contract</fullName>
            </value>
            <value>
                <fullName>Copy of T&amp;C&apos;s</fullName>
            </value>
            <value>
                <fullName>Credit License</fullName>
            </value>
            <value>
                <fullName>Critical information summary</fullName>
            </value>
            <value>
                <fullName>Data update</fullName>
            </value>
            <value>
                <fullName>Developer/Support enquiries</fullName>
            </value>
            <value>
                <fullName>Direct Debit Request (DDR)</fullName>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
            </value>
            <value>
                <fullName>EDMS DD</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Failed Payment Common Codes &amp; Reasons</fullName>
            </value>
            <value>
                <fullName>Fee Confirmation</fullName>
            </value>
            <value>
                <fullName>Fee Structure - Who Pays</fullName>
            </value>
            <value>
                <fullName>Financial Details</fullName>
            </value>
            <value>
                <fullName>Financial Reports Pending</fullName>
            </value>
            <value>
                <fullName>Remove User</fullName>
            </value>
            <value>
                <fullName>Add Device</fullName>
            </value>
            <value>
                <fullName>Remove Device</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Onboarding.recordType-meta.xml
<RecordType>
    <fullName>Onboarding</fullName>
    <active>true</active>
    <businessProcess>Onboarding</businessProcess>
    <description>Used by Onboarding team to replace requests sent to Sales@ezidebit.com.au</description>
    <label>Onboarding</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>Business of Motion</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Client Connect</fullName>
            </value>
            <value>
                <fullName>Clouding Around</fullName>
            </value>
            <value>
                <fullName>Clubworx</fullName>
            </value>
            <value>
                <fullName>Concise Digital</fullName>
            </value>
            <value>
                <fullName>Console Gateway</fullName>
            </value>
            <value>
                <fullName>CyberSource Direct</fullName>
            </value>
            <value>
                <fullName>DanceStudio-Pro</fullName>
            </value>
            <value>
                <fullName>DebtCol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OnboardingCaseCtrl.cls
public without sharing class OnboardingCaseCtrl  {
    @AuraEnabled(cacheable = false)
    public static void createAddEftposCase(String clientId, String businessNumber, String requesterEmailAddress, String selectedEftposDevices) {
        try {
            Group owner = [
                SELECT Id 
                FROM Group 
                WHERE DeveloperName = 'Onboarding' AND Type = 'Queue' 
                LIMIT 1
            ];

            Id caseRecordTypeId = Schema.SObjectType.Case
                .getRecordTypeInfosByDeveloperName()
                .get('Onboarding')
                .getRecordTypeId();

            businessNumber = businessNumber.deleteWhitespace();
            List<Account> existingAccounts = getexistingAccountRecords(clientId, businessNumber);

            Case c = new Case();
            c.RecordTypeId = caseRecordTypeId;
            c.OwnerId = owner.Id;
            c.AccountId = existingAccounts.get(0).Id;
            c.Category__c = 'Service (multi-MID)';
            c.Sub_Category__c = 'Add Device';
            c.Status = 'New';
            c.Subject = 'New Request - ' + existingAccounts.get(0).Industry + ' - Existing Merchant (Multi MID)';
            c.Description = 
                'EFTPOS Device Request\n' +
                '---------------------------\n' +
                'Business Name: ' + existingAccounts.get(0).Name + '\n' +
                'Payments ID: ' + clientId + '\n' +
                'ABN: ' + businessNumber + '\n' +
                'Requesters email address: '+ requesterEmailAddress +' \n' +
                '-------- Devices to Add --------\n' +
                'Number of devices to be added: ' + selectedEftposDevices;

            insert c;
            
            //Send Confirmation email
            sendConfirmationEmail(c.Id, requesterEmailAddress);

        } catch (Exception ex) {
            System.debug('Exception: ' + ex);
        }
    }

    @AuraEnabled
    public static void createCaseToRemoveMultipleMerchant(String clientId, String businessNumber, String requesterEmailAddress, String merchants) {
        businessNumber = businessNumber.deleteWhitespace();
        RecordType rc = [SELECT Id FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'Onboarding' LIMIT 1];
        Group owner = [SELECT Id FROM Group WHERE DeveloperName = 'Onboarding' AND Type = 'Queue' LIMIT 1];
        List<Account> existingAccounts = [
            SELECT Id, Name, Industry
            FROM Account
            WHERE Client_Code__c = :clientId 
              AND Unformatted_ABN__c = :businessNumber
        ];

        List<Object> merchantRecords = (List<Object>) JSON.deserializeUntyped(merchants);
        System.debug(merchantRecords);
        
        String formattedMerchants = '';
        for (Integer i = 0; i < merchantRecords.size(); i++) {
            Map<String, Object> eachMerchant = (Map<String, Object>)merchantRecords[i];
            if ((Boolean)eachMerchant.get('isValid') == true) {
                String formattedString = 'tradingName: ' + (String)eachMerchant.get('tradingName') + ',\n' +
                                         'email: ' + (String)eachMerchant.get('email') + ',\n' +
                                         'clientId: ' + (String)eachMerchant.get('clientId') + ';';
                
                if (i < merchantRecords.size() - 1) {
                    formattedMerchants += formattedString + '\n';
                } else {
                    formattedMerchants += formattedString;
                }
            }
        }

        Case c = new Case();
        c.RecordTypeId = rc.Id;
        c.OwnerId = owner.Id;
        c.AccountId = existingAccounts.get(0).Id;
        c.Category__c = 'Service (multi-MID)';
        c.Sub_Category__c = 'Remove User';
        c.Status = 'New';
        c.Subject = 'New Request - ' + existingAccounts.get(0).Industry + ' - Existing Merchant (Multi MID)';
        c.Origin = 'Web';
        c.Description =
            'Remove Multiple Merchants\n' +
            '---------------------------\n' +
            'Trading Name: ' + existingAccounts.get(0).Name + '\n' +
            'Payments ID: ' + clientId + '\n' +
            'ABN: ' + businessNumber + '\n' +
            'Requesters email address: ' + requesterEmailAddress + '\n' +
            '-------- Merchants to Remove --------\n'
            + formattedMerchants;

        insert c;
      
        //Send Confirmation email
        sendConfirmationEmail(c.Id, requesterEmailAddress);
    }

    @AuraEnabled(cacheable = false)
    public static void createRemoveEftposDevicesCase(String clientId, String businessNumber, String requesterEmailAddress, String selectedEftposDevices) {
        try {
            List<Object> deviceRecords = (List<Object>) JSON.deserializeUntyped(selectedEftposDevices);
            String formattedDevices = '';

            for (Integer i = 0; i < deviceRecords.size(); i++) {
                Map<String, Object> eachMerchant = (Map<String, Object>) deviceRecords[i];

                if ((Boolean) eachMerchant.get('isValid') == true) {
                    String serialNo = (String) eachMerchant.get('serialNo');
                    String reasonToRemoveOpt = (String) eachMerchant.get('reasonToRemoveOpt');
                    String reasonToRemoveDesc = (String) eachMerchant.get('reasonToRemoveDesc');

                    if (String.isNotBlank(serialNo)) {
                        formattedDevices += 'Device ' + (i + 1) + ':\n';
                        formattedDevices += 'Serial No: ' + serialNo + '\n';
                        formattedDevices += 'Reason to Remove: ' + (reasonToRemoveOpt != null ? reasonToRemoveOpt : '') + '\n';

                        if (String.isNotBlank(reasonToRemoveDesc)) {
                            formattedDevices += 'Remove Reason Details: ' + reasonToRemoveDesc + '\n';
                        }

                        formattedDevices += '\n';
                    }
                }
            }

            Group owner = [
                SELECT Id 
                FROM Group 
                WHERE DeveloperName = 'Onboarding' AND Type = 'Queue' 
                LIMIT 1
            ];

            Id caseRecordTypeId = Schema.SObjectType.Case
                .getRecordTypeInfosByDeveloperName()
                .get('Onboarding')
                .getRecordTypeId();

            businessNumber = businessNumber.deleteWhitespace();
            List<Account> existingAccounts = getexistingAccountRecords(clientId, businessNumber);

            Case c = new Case();
            c.RecordTypeId = caseRecordTypeId;
            c.OwnerId = owner.Id;
            c.AccountId = existingAccounts.get(0).Id;
            c.Category__c = 'Service (multi-MID)';
            c.Sub_Category__c = 'Remove Device';
            c.Status = 'New';
            c.Subject = 'New Request - ' + existingAccounts.get(0).Industry + ' - Existing Merchant (Multi MID)';
            c.Description = 
                'Remove Multiple EFTPOS Devices Request\n' +
                '---------------------------\n' +
                'Business Name: ' + existingAccounts.get(0).Name + '\n' +
                'Payments ID: ' + clientId + '\n' +
                'ABN: ' + businessNumber + '\n' +
                'Requesters email address: '+ requesterEmailAddress +' \n' +
                '-------- Devices to Remove --------\n' +
                formattedDevices;

            insert c;

            //Send Confirmation email
            sendConfirmationEmail(c.Id, requesterEmailAddress);

        } catch (Exception ex) {
            System.debug('Exception: ' + ex);
        }
    }

    public static List<Account> getexistingAccountRecords(String clientId, String businessNumber) {
        return [
            SELECT Id, Name, Unformatted_ABN__c, Client_Code__c, Industry, 
                   Software__c, Account_Status__c, API_Capability__c, 
                   Opportunity_ID__r.Product_Requested__c
            FROM Account
            WHERE Client_Code__c = :clientId 
              AND Unformatted_ABN__c = :businessNumber
        ];
    }

    public static void sendConfirmationEmail(Id caseId, String requesterEmailAddress) {

    String templateDevName = 'Auto_Confirmation_Email_for_New_Service_Ext_Requests';
    if (String.isBlank(requesterEmailAddress) || caseId == null) {
        throw new AuraHandledException('Invalid parameters: requester email or case ID is missing.');
    }

    try {
        Contact recipient = [
            SELECT Id, FirstName, Email 
            FROM Contact 
            WHERE Email = :requesterEmailAddress 
            LIMIT 1
        ];

        EmailTemplate template = [
            SELECT Id 
            FROM EmailTemplate 
            WHERE DeveloperName = :templateDevName 
            LIMIT 1
        ];
        
        // Prepare the email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(recipient.Id); 
        mail.setWhatId(caseId);         
        mail.setTemplateId(template.Id);
        mail.setSaveAsActivity(true);

        // Send the email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    } catch (Exception ex) {
        System.debug('Email Sending Error: ' + ex);
        throw new AuraHandledException('Failed to send confirmation email: ' + ex.getMessage());
    }
}

}