force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezidebit</fullName>
            </value>
            <value>
                <fullName>Eway</fullName>
            </value>
            <value>
                <fullName>Global Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Entity_types__c.field-meta.xml
<CustomField>
    <fullName>Entity_types__c</fullName>
    <description>Type of entity the business is - e.g. Sole Trader, Trust etc</description>
    <label>Entity types</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved Deposit Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Non-Public Offer Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Public Offer Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Fund (Fund Type Unknown)</fullName>
            </value>
            <value>
                <fullName>ATO Regulated Self-Managed Superannuation Fund</fullName>
            </value>
            <value>
                <fullName>Australian Private Company</fullName>
            </value>
            <value>
                <fullName>Australian Public Company</fullName>
            </value>
            <value>
                <fullName>Cash Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government APRA Regulated Public Sector Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government APRA Regulated Public Sector Scheme</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Cash Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Company</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Co-operative</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Corporate Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Investment Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Services Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Trading Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Fixed Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Fixed Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Hybrid Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Listed Public Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Non-Regulated Super Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Other Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Other Unincorporated Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Partnership</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Pooled Development Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Private Company</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Public Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Partner_Logo_URL__c</fullName>
    <description>Url to partner logo loaded to documents folder (mapped from lead)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Logo URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>360 Membership</fullName>
            </value>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Accelerware - Sports Performance Systems</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>All Inn 1</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>ASSA</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>Billing Bureau</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Booking Boss</fullName>
            </value>
            <value>
                <fullName>Bookings Essential</fullName>
            </value>
            <value>
                <fullName>Business Of Motion</fullName>
            </value>
            <value>
                <fullName>Causeview</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Glofox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSA__c/CSA__c.object-meta.xml
<CustomObject>
    <description>Object holds CSA online templates</description>
    <label>CSA</label>
    <nameField>
        <displayFormat>CSA{00000000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CSA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CSAs</relationshipLabel>
    <relationshipName>CSAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CSA__c/fields/Use_Partner_Logo__c.field-meta.xml
<CustomField>
    <fullName>Use_Partner_Logo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It indicate to use partner logo or not.</description>
    <label>Use Partner Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSA__c.field-meta.xml
<CustomField>
    <fullName>CSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the CSA created</inlineHelpText>
    <label>CSA</label>
    <referenceTo>CSA__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isClosedAddProduct__c.field-meta.xml
<CustomField>
    <fullName>isClosedAddProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isClosedAddProduct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isClosedCSA__c.field-meta.xml
<CustomField>
    <fullName>isClosedCSA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isClosedCSA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>Business of Motion</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Client Connect</fullName>
            </value>
            <value>
                <fullName>Clouding Around</fullName>
            </value>
            <value>
                <fullName>Clubworx</fullName>
            </value>
            <value>
                <fullName>Concise Digital</fullName>
            </value>
            <value>
                <fullName>Console Gateway</fullName>
            </value>
            <value>
                <fullName>CyberSource Direct</fullName>
            </value>
            <value>
                <fullName>DanceStudio-Pro</fullName>
            </value>
            <value>
                <fullName>DebtCol</fullName>
            </value>
            <value>
                <fullName>Glofox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Configuration__c/Partner_Configuration__c.object-meta.xml
<CustomObject>
    <label>Partner Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Configuration__c/fields/API_Integration_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Integration_Method__c</fullName>
    <label>API Integration Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single API</fullName>
            </value>
            <value>
                <fullName>Ezidebit API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Configuration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>It indicates merchant&apos;s brand</description>
    <inlineHelpText>It indicates merchant&apos;s brand</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eway</fullName>
            </value>
            <value>
                <fullName>Ezidebit</fullName>
            </value>
            <value>
                <fullName>GlobalPayments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Configuration__c/fields/Partner_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Partner_Logo_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Logo URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KYC_EftposBiller_Controller_Test.cls
@isTest
public class KYC_EftposBiller_Controller_Test  {
     @TestSetup
     static void setupData() {
          Partner_Configuration__c spm03 = new Partner_Configuration__c(
               Name = 'Glofox',
               API_Integration_Method__c = 'Single API',
               Brand__c = 'Eway',
               Partner_Logo_URL__c = 'https://ezidebit--ezifull.sandbox.file.force.com/servlet/servlet.ImageServer?id=0158s000005BwozAAC&oid=00D8s000005vB8j'
          );
          insert spm03;
          Account acc = (Account) TestDataFactory.createSObject(
               new Account(),
               'TestDataFactory.AccountDefaults',
               true
          );
          Contact con = (Contact) TestDataFactory.createSObject(
               new Contact(accountid = acc.Id),
               'TestDataFactory.ContactDefaults',
               true
          );
          Opportunity opp = (Opportunity) TestDataFactory.createSObject(
               new Opportunity(accountid = acc.Id),
               'TestDataFactory.OpportunityDefaults',
               true
          );
          CSA__c csa = (CSA__C) TestDataFactory.createSObject(
               new CSA__c(Opportunity__c = opp.id)
          );
          acc.Entity_types__c = 'Australian Private Company';
          acc.Software__c = 'Glofox';
          update acc;
          csa.Use_Partner_Logo__c = true;
          insert csa;
     }

     @isTest
     private static void Test_LoadData() {
          Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
          CSA__c csa = [SELECT Id FROM CSA__c LIMIT 1];
          Account acc = [SELECT Id, Entity_types__c FROM Account LIMIT 1];

          ApexPages.currentPage().getParameters().put('oppid', opp.Id);
          ApexPages.currentPage().getParameters().put('csa', csa.Id);

          Test.startTest();
          KYC_EftposBiller_Controller controller = new KYC_EftposBiller_Controller();
          String supportPhoneNo = controller.supportPhoneNo;
          String software = controller.software;
          String nextPage = controller.nextPageName;
          String logo = controller.logo;
          Test.stopTest();
          system.assertEquals('Glofox', software, 'Incorrect software');
          system.assertEquals(
               '1800 106 565',
               supportPhoneNo,
               'Incorrect support phone number'
          );
          system.assertEquals(
               'KYC_CompanyOfficers',
               nextPage,
               'Incorrect next page'
          );
          system.assertEquals(
               'https://ezidebit--ezifull.sandbox.file.force.com/servlet/servlet.ImageServer?id=0158s000005BwozAAC&oid=00D8s000005vB8j',
               logo,
               'Incorrect logo'
          );
     }

     @isTest
     private static void Test_Init() {
          CSA__c csa = [SELECT Id FROM CSA__c LIMIT 1];
          Opportunity opp = [
               SELECT Id, isClosedCSA__c, isClosedAddProduct__c
               FROM Opportunity
               LIMIT 1
          ];
          opp.isClosedCSA__c = true;
          opp.isClosedAddProduct__c = true;
          update opp;

          ApexPages.currentPage().getParameters().put('oppid', opp.Id);
          ApexPages.currentPage().getParameters().put('csa', csa.Id);

          Test.startTest();
          KYC_EftposBiller_Controller controller = new KYC_EftposBiller_Controller();
          Pagereference result = controller.init();
          Test.stopTest();
          PageReference pageExcept = new PageReference(
               'https://www.ezidebit.com/en-au/application-in-progress'
          );
          System.assertEquals(pageExcept.getUrl(), result.getUrl());
     }
     
}