force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ezidebit</fullName>
            </value>
            <value>
                <fullName>Eway</fullName>
            </value>
            <value>
                <fullName>Global Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EFTPOS_Provider__c.field-meta.xml
<CustomField>
    <fullName>EFTPOS_Provider__c</fullName>
    <description>EFTPOS Provider value, currently we have got 2 Smartpay, Quest</description>
    <label>EFTPOS Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SmartPay</fullName>
            </value>
            <value>
                <fullName>Quest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Entity_types__c.field-meta.xml
<CustomField>
    <fullName>Entity_types__c</fullName>
    <description>Type of entity the business is - e.g. Sole Trader, Trust etc</description>
    <label>Entity types</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved Deposit Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Non-Public Offer Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Public Offer Fund</fullName>
            </value>
            <value>
                <fullName>APRA Regulated Fund (Fund Type Unknown)</fullName>
            </value>
            <value>
                <fullName>ATO Regulated Self-Managed Superannuation Fund</fullName>
            </value>
            <value>
                <fullName>Australian Private Company</fullName>
            </value>
            <value>
                <fullName>Australian Public Company</fullName>
            </value>
            <value>
                <fullName>Cash Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government APRA Regulated Public Sector Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government APRA Regulated Public Sector Scheme</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Cash Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Company</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Co-operative</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Corporate Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Investment Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Services Management Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Discretionary Trading Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Fixed Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Fixed Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Hybrid Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Limited Partnership</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Listed Public Unit Trust</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Non-Regulated Super Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Other Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Other Unincorporated Entity</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Partnership</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Pooled Development Fund</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Private Company</fullName>
            </value>
            <value>
                <fullName>Commonwealth Government Public Company</fullName>
            </value>
            <value>
                <fullName>Individual/Sole Trader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Partner_Logo_URL__c</fullName>
    <description>Url to partner logo loaded to documents folder (mapped from lead)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Partner Logo URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>360 Membership</fullName>
            </value>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Accelerware - Sports Performance Systems</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>All Inn 1</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>ASSA</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>Billing Bureau</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>Booking Boss</fullName>
            </value>
            <value>
                <fullName>Bookings Essential</fullName>
            </value>
            <value>
                <fullName>Business Of Motion</fullName>
            </value>
            <value>
                <fullName>Causeview</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Support_Phone_Number__c</fullName>
    <formula>if (ISPICKVAL(BillingCountryCode,&quot;NZ&quot;) &amp;&amp;  ISPICKVAL( Brand__c , &quot;Ezidebit&quot;) ,&quot;0800 478 483&quot;,
if (ISPICKVAL(BillingCountryCode,&quot;NZ&quot;) &amp;&amp;  ISPICKVAL( Brand__c , &quot;Eway&quot;) ,&quot;0800 392 947&quot;,
if (ISPICKVAL(BillingCountryCode,&quot;NZ&quot;),&quot;0800 478 483&quot;,
if (ISPICKVAL(BillingCountryCode,&quot;AU&quot;) &amp;&amp;  ISPICKVAL( Brand__c , &quot;Ezidebit&quot;) ,&quot;1300 763 256&quot;,
if (ISPICKVAL(BillingCountryCode,&quot;AU&quot;) &amp;&amp;  ISPICKVAL( Brand__c , &quot;Eway&quot;) ,&quot;1800 106 565&quot;,&quot;1300 763 256&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Support Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>365 Mechanix</fullName>
            </value>
            <value>
                <fullName>Accelerware</fullName>
            </value>
            <value>
                <fullName>Active Billing</fullName>
            </value>
            <value>
                <fullName>Active World</fullName>
            </value>
            <value>
                <fullName>AgilityCIS</fullName>
            </value>
            <value>
                <fullName>AimyPlus</fullName>
            </value>
            <value>
                <fullName>Alphasys</fullName>
            </value>
            <value>
                <fullName>AnytimeOffice</fullName>
            </value>
            <value>
                <fullName>Appello</fullName>
            </value>
            <value>
                <fullName>ASI</fullName>
            </value>
            <value>
                <fullName>Avocado</fullName>
            </value>
            <value>
                <fullName>AX3 Group</fullName>
            </value>
            <value>
                <fullName>Bark.com</fullName>
            </value>
            <value>
                <fullName>Baseplan</fullName>
            </value>
            <value>
                <fullName>Becklyn</fullName>
            </value>
            <value>
                <fullName>Better Clinics</fullName>
            </value>
            <value>
                <fullName>BIT</fullName>
            </value>
            <value>
                <fullName>Business of Motion</fullName>
            </value>
            <value>
                <fullName>Centaman</fullName>
            </value>
            <value>
                <fullName>Cerebiz</fullName>
            </value>
            <value>
                <fullName>Cirrus Technologies</fullName>
            </value>
            <value>
                <fullName>Clearwater</fullName>
            </value>
            <value>
                <fullName>Client Connect</fullName>
            </value>
            <value>
                <fullName>Clouding Around</fullName>
            </value>
            <value>
                <fullName>Clubworx</fullName>
            </value>
            <value>
                <fullName>Concise Digital</fullName>
            </value>
            <value>
                <fullName>Console Gateway</fullName>
            </value>
            <value>
                <fullName>CyberSource Direct</fullName>
            </value>
            <value>
                <fullName>DanceStudio-Pro</fullName>
            </value>
            <value>
                <fullName>DebtCol</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KYC_EftposBiller_Controller.cls
public without sharing class KYC_EftposBiller_Controller {
     private Account acc;
     private Opportunity opp { get; set; }
     public String oppid { get; set; }
     public String csaid { get; set; }
     public String accid { get; set; }
     public String origin { get; set; }
     public String nextPageName { get; set; }
     public String conid { get; set; }

     public String logo { get; set; }
     public String supportPhoneNo { get; set; }
     public String software { get; set; }
     public Boolean isEzidebitBrand { get; set; }
     public String brandType { get; set; }

     public KYC_EftposBiller_Controller() {
          oppid = system.currentPageReference().getParameters().get('oppId');
          csaid = system.currentPageReference().getParameters().get('csa');
          origin = system.currentPageReference().getParameters().get('origin');
          conid = system.currentPageReference().getParameters().get('conid');
          logo = getLogo(oppId);

          opp = getOpp(oppId);
          accid = opp.Accountid;

          acc = [
               SELECT
                    software__c,
                    Brand__c,
                    Support_phone_number__c,
                    EFTPOS_Provider__c,
                    Entity_types__c
               FROM Account
               WHERE Id = :opp.AccountId
          ];
          software = acc.software__c;
          isEzidebitBrand =
               String.isBlank(acc.Brand__c) ||
               (String.isNotBlank(acc.Brand__c) && acc.Brand__c == 'Ezidebit');
          supportPhoneNo = acc.Support_phone_number__c;
          brandType = acc.Brand__c;

          if (acc.Entity_types__c.contains('Government')) {
               nextPageName = 'KYC_Execution';
          } else if (acc.Entity_types__c == 'Individual/Sole Trader') {
               nextPageName = 'KYC_VerifyIndividual';
          } else {
               nextPageName = 'KYC_CompanyOfficers';
          }
     }

     public PageReference init() {
          return null;
     }

     private Opportunity getOpp(String oppId) {
          Opportunity opp = [
               SELECT Accountid, Software__c
               FROM Opportunity
               WHERE Id = :oppid
          ];
          return opp;
     }

     private String getLogo(String oppId) {
         Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :oppId];
         if (String.isNotBlank(opp?.AccountId)) {
             Account acc = [SELECT Partner_Logo_URL__c FROM Account WHERE Id = :opp.AccountId];
             return acc?.Partner_Logo_URL__c;
         }
         return '';
    }
}