force-app/main/default/objects/Partner_Configuration__c/Partner_Configuration__c.object-meta.xml
<CustomObject>
    <label>Partner Configuration</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Configuration__c/fields/Multi_MID_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Multi_MID_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>when value is true partner Multi-MID is enabled</description>
    <label>Multi-MID Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Configuration__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Configurations</relationshipLabel>
    <relationshipName>Partner_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Configuration__c/fields/Payment_Solutions__c.field-meta.xml
<CustomField>
    <fullName>Payment_Solutions__c</fullName>
    <label>Payment Solutions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BPAY</fullName>
            </value>
            <value>
                <fullName>Business Security</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>EFTPOS</fullName>
            </value>
            <value>
                <fullName>Online Payments</fullName>
            </value>
            <value>
                <fullName>PayTo</fullName>
            </value>
            <value>
                <fullName>Phone Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerConfigHelper.cls
public inherited sharing class PartnerConfigHelper {
    @AuraEnabled
    public static List<Partner_Configuration__c> getPartnerConfigsViaAccountId(Id accountId){
        return [SELECT Id, Name, Payment_Solutions__c FROM Partner_Configuration__c WHERE Partner_Account__c = :accountId];
    }

    public static Map<String, Partner_Configuration__c> getPartnerAccountBySoftware(Set<String> softwareList){
        Map<String, Partner_Configuration__c> partnerAccountBySoftware = new Map<String, Partner_Configuration__c>();
        List<Partner_Configuration__c> configList = [SELECT Name, Multi_MID_Enabled__c, Partner_Account__r.Name FROM Partner_Configuration__c WHERE Name IN :softwareList];
        for(Partner_Configuration__c config : configList){
            partnerAccountBySoftware.put(config.Name, config);
        }
        return partnerAccountBySoftware;
    }
}