force-app/main/default/objects/OJ_Button_Label__mdt/OJ_Button_Label__mdt.object-meta.xml
<CustomObject>
    <label>OJ Button Label</label>
    <pluralLabel>OJ Button Labels</pluralLabel>
</CustomObject>

force-app/main/default/objects/OJ_Button_Label__mdt/fields/Button1_Label__c.field-meta.xml
<CustomField>
    <fullName>Button1_Label__c</fullName>
    <label>Button1 Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OJ_Button_Label__mdt/fields/Button2_Label__c.field-meta.xml
<CustomField>
    <fullName>Button2_Label__c</fullName>
    <label>Button2 Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OJButtonsHelper.cls
public without sharing class OJButtonsHelper {
    @AuraEnabled(cacheable=true)
    public static List<OJ_Button_Label__mdt> getFormButtonLabels(String brand) {
        List<String> fields = new List<String>{'DeveloperName','Button1_Label__c','Button2_Label__c'};
        String buttonsQuery = 'SELECT ' + String.join(fields, ', ') + ' FROM OJ_Button_Label__mdt WHERE Brand__c = :brand ORDER BY DeveloperName';
        List<OJ_Button_Label__mdt> formButtons = Database.query(buttonsQuery);
        if(formButtons.isEmpty()){
            throw new CustomException('No labels found for the brand: ' + brand);
        }

        return formButtons;
    }
}